MODEL:
    TYPE: 'gender'
    # TYPE: 'race'
    BUDGET_NUM_MODELS: 5
    BUDGET_INPUT_CHANNELS: 2
    GPU_ENABLED: 1
TRAIN:
    TRAIN_META: 'data/train_metadata_template.csv'
    TRAIN_BIN_FEATS: 'data/train_features_template.bin'
    VAL_META: 'data/train_metadata_template.csv'
    VAL_BIN_FEATS: 'data/train_features_template.bin'
    CHECKPOINT_DIR: 'checkpoints'
    RESUME_FROM_CHECKPOINT: 0
    RESUME_CHECKPOINT_FILE: ''

    FC_BATCH_SIZE: 400
    TRAIN_BATCH_SIZE: 40
    VAL_BATCH_SIZE: 400
    NUM_WORKERS: 4
    PIN_MEMORY: 0

    TRAIN_STEPS: 6000
    SAVE_STEP: 1
    PRINT_FREQ: 10

    TASK_FC_TRAIN_FIRST: 1
    TASK_FC_INITIAL_LR: 0.001
    TASK_FC_TRAIN_BATCHES: 600
    TASK_FC_LR_SCH_GAMMA: 0.1
    TASK_FC_LR_SCH_DECAY_BATCHES: 2000
    TASK_FC_WARMUP_BATCHES: 4000
    TASK_FC_WARMUP_LR_SCH_MULTIPLIER: 12
    TASK_FC_BATCHES_PER_OPT_STEP: 2

    USE_BUDGET_RESTARTING: 1
    BUDGET_RESTART_STEP: 30
    BUDGET_INITIAL_BATCHES: 300
    BUDGET_LOSS_XENTROPY_UNIFORM: 1
    BUDGET_LOSS_SCALE: 10.0

    DEGRADATION_BATCHES_PER_OPT_STEP: 1
    DEGRADATION_BATCHES_ALONE: 120

    MONITOR_BUDGET: 1
    BUDGET_MONITOR_TRAIN_ACC_THRESH: 0.9
    BUDGET_PLATEAU_THRESH: 10
    BUDGET_BATCHES_PER_OPT_STEP: 1
    BUDGET_TRAIN_BATCHES_PER_CHECK: 120

    TASK_BATCHES_PER_OPT_STEP: 1
    TASK_VAL_PROBE_BATCHES: 20

    LR_SCH_DECAY_STEP: 10
    LR_SCH_GAMMA: 0.5

    INITIAL_LR_DEGRADATION: 0.0001    
    INITIAL_LR_BUDGET: 0.001
TEST:
    CHECKPOINT_FILE: 'checkpoints/latest.pth.tar'
    INPUT_FEATURES_CSV: 'data/inference_input_template.csv'
    OUTPUT_FEATURES_CSV: 'results/debiased_features.csv'
